version: '3.6'

services:
  xteve:
    image: ghcr.io/smeetsee/docker-xteve:main
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: xteve
    volumes:
      - ./root:/home/xteve/.xteve
      - ./tmp:/tmp/xteve
    ports:
      - 34400:34400
    restart: unless-stopped
